[data]
batch_size = 512
shuffle = true
num_workers = 4

[training]
epochs = 20
batch_size = 512
optimizer = "adam"
criterion = "crossentropy"
lr = 0.003
weight_decay = 1e-4
lrfinder = { numiter = 600, endlr = 10, startlr = 1e-2 }
